# Generated by Django 5.1.5 on 2025-02-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
