# Generated by Django 5.1.5 on 2025-02-03 06:57

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=projects.models.upload_to)),
                ('period', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateField(blank=True)),
            ],
        ),
    ]
