# Generated by Django 5.1.5 on 2025-02-05 04:37

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_uploaded_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateField(blank=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, upload_to=projects.models.upload_to, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='period',
            field=models.CharField(blank=True, max_length=150, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Вкратце'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
    ]
