# Generated by Django 5.1.5 on 2025-02-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_options_alter_projects_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='choosen',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
