# Generated by Django 5.1.5 on 2025-02-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_choosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='coordinate_x',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Широта(x)'),
        ),
        migrations.AddField(
            model_name='projects',
            name='coordinate_y',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Долгота(y)'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='choosen',
            field=models.BooleanField(blank=True, default=False, verbose_name='Избранный'),
        ),
    ]
