# Generated by Django 5.1.5 on 2025-02-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='user_id',
            field=models.CharField(default=12345, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
