# Generated by Django 5.1.5 on 2025-02-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userlocation_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlocation',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='latitude',
            field=models.FloatField(verbose_name='Широта(x)'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота(y)'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Временная метка'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID (идентификатор)'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user_nickname',
            field=models.CharField(max_length=255, verbose_name='Никнейм'),
        ),
    ]
