# Generated by Django 5.1.5 on 2025-02-03 06:19

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=news.models.upload_to)),
                ('created_at', models.DateField(blank=True)),
            ],
        ),
    ]
